export default function FoodSelector(props) {
  const foodSelectorList = [
    { id: 1, name: "Apple", calories: 95, type: "fruits" },
    { id: 2, name: "Banana", calories: 105, type: "fruits" },
    { id: 3, name: "Orange", calories: 62, type: "fruits" },
    { id: 4, name: "Grapes", calories: 62, type: "fruits" },
    { id: 5, name: "Strawberry", calories: 49, type: "fruits" },
    { id: 6, name: "Blueberry", calories: 84, type: "fruits" },
    { id: 7, name: "Mango", calories: 150, type: "fruits" },
    { id: 8, name: "Pineapple", calories: 82, type: "fruits" },
    { id: 9, name: "Watermelon", calories: 85, type: "fruits" },
    { id: 10, name: "Peach", calories: 59, type: "fruits" },
    { id: 11, name: "Pear", calories: 101, type: "fruits" },
    { id: 12, name: "Kiwi", calories: 42, type: "fruits" },
    { id: 13, name: "Papaya", calories: 119, type: "fruits" },
    { id: 14, name: "Cherry", calories: 87, type: "fruits" },
    { id: 15, name: "Plum", calories: 30, type: "fruits" },
    { id: 16, name: "Lemon", calories: 17, type: "fruits" },
    { id: 17, name: "Lime", calories: 20, type: "fruits" },
    { id: 18, name: "Avocado", calories: 240, type: "fruits" },
    { id: 19, name: "Coconut", calories: 283, type: "fruits" },
    { id: 20, name: "Pomegranate", calories: 234, type: "fruits" },
    { id: 21, name: "Raspberry", calories: 64, type: "fruits" },
    { id: 22, name: "Blackberry", calories: 62, type: "fruits" },
    { id: 23, name: "Cantaloupe", calories: 54, type: "fruits" },
    { id: 24, name: "Honeydew", calories: 64, type: "fruits" },
    { id: 25, name: "Fig", calories: 37, type: "fruits" },
    { id: 26, name: "Date", calories: 66, type: "fruits" },
    { id: 27, name: "Apricot", calories: 17, type: "fruits" },
    { id: 28, name: "Dragon Fruit", calories: 60, type: "fruits" },
    { id: 29, name: "Guava", calories: 112, type: "fruits" },
    { id: 30, name: "Passionfruit", calories: 17, type: "fruits" },
    { id: 31, name: "Tangerine", calories: 47, type: "fruits" },
    { id: 32, name: "Clementine", calories: 35, type: "fruits" },
    { id: 33, name: "Nectarine", calories: 62, type: "fruits" },
    { id: 34, name: "Grapefruit", calories: 52, type: "fruits" },
    { id: 35, name: "Cranberry", calories: 46, type: "fruits" },
    { id: 36, name: "Boysenberry", calories: 68, type: "fruits" },
    { id: 37, name: "Mulberry", calories: 60, type: "fruits" },
    { id: 38, name: "Starfruit", calories: 31, type: "fruits" },
    { id: 39, name: "Persimmon", calories: 118, type: "fruits" },
    { id: 40, name: "Lychee", calories: 66, type: "fruits" },
    { id: 41, name: "Longan", calories: 38, type: "fruits" },
    { id: 42, name: "Rambutan", calories: 75, type: "fruits" },
    { id: 43, name: "Jackfruit", calories: 157, type: "fruits" },
    { id: 44, name: "Red Currant", calories: 63, type: "fruits" },
    { id: 45, name: "Black Currant", calories: 71, type: "fruits" },
    { id: 46, name: "Gooseberry", calories: 66, type: "fruits" },
    { id: 47, name: "Prune", calories: 67, type: "fruits" },
    { id: 48, name: "Plantain", calories: 218, type: "fruits" },
    { id: 49, name: "Mandarin", calories: 47, type: "fruits" },
    { id: 50, name: "Ugli Fruit", calories: 45, type: "fruits" },
    { id: 51, name: "Blood Orange", calories: 70, type: "fruits" },
    { id: 52, name: "Satsuma", calories: 47, type: "fruits" },
    { id: 53, name: "Galia Melon", calories: 60, type: "fruits" },
    { id: 54, name: "Asian Pear", calories: 51, type: "fruits" },
    { id: 55, name: "Quince", calories: 52, type: "fruits" },
    { id: 56, name: "Tamarind", calories: 239, type: "fruits" },
    { id: 57, name: "Soursop", calories: 148, type: "fruits" },
    { id: 58, name: "Sapodilla", calories: 200, type: "fruits" },
    { id: 59, name: "Kumquat", calories: 71, type: "fruits" },
    { id: 60, name: "Elderberry", calories: 73, type: "fruits" },

    { id: 61, name: "Carrot", calories: 25, type: "vegetables" },
    { id: 62, name: "Broccoli", calories: 55, type: "vegetables" },
    { id: 63, name: "Spinach", calories: 23, type: "vegetables" },
    { id: 64, name: "Kale", calories: 33, type: "vegetables" },
    { id: 65, name: "Potato", calories: 163, type: "vegetables" },
    { id: 66, name: "Sweet Potato", calories: 112, type: "vegetables" },
    { id: 67, name: "Tomato", calories: 22, type: "vegetables" },
    { id: 68, name: "Onion", calories: 44, type: "vegetables" },
    { id: 69, name: "Garlic", calories: 5, type: "vegetables" },
    { id: 70, name: "Cauliflower", calories: 25, type: "vegetables" },
    { id: 71, name: "Cabbage", calories: 22, type: "vegetables" },
    { id: 72, name: "Lettuce", calories: 5, type: "vegetables" },
    { id: 73, name: "Cucumber", calories: 16, type: "vegetables" },
    { id: 74, name: "Zucchini", calories: 33, type: "vegetables" },
    { id: 75, name: "Bell Pepper", calories: 30, type: "vegetables" },
    { id: 76, name: "Eggplant", calories: 35, type: "vegetables" },
    { id: 77, name: "Mushroom", calories: 15, type: "vegetables" },
    { id: 78, name: "Celery", calories: 10, type: "vegetables" },
    { id: 79, name: "Asparagus", calories: 27, type: "vegetables" },
    { id: 80, name: "Corn", calories: 96, type: "vegetables" },
    { id: 81, name: "Radish", calories: 16, type: "vegetables" },
    { id: 82, name: "Beetroot", calories: 43, type: "vegetables" },
    { id: 83, name: "Brussels Sprouts", calories: 38, type: "vegetables" },
    { id: 84, name: "Turnip", calories: 36, type: "vegetables" },
    { id: 85, name: "Parsnip", calories: 75, type: "vegetables" },
    { id: 86, name: "Okra", calories: 33, type: "vegetables" },
    { id: 87, name: "Leek", calories: 54, type: "vegetables" },
    { id: 88, name: "Artichoke", calories: 60, type: "vegetables" },
    { id: 89, name: "Chili Pepper", calories: 18, type: "vegetables" },
    { id: 90, name: "Pumpkin", calories: 49, type: "vegetables" },
    { id: 91, name: "Butternut Squash", calories: 82, type: "vegetables" },
    { id: 92, name: "Acorn Squash", calories: 115, type: "vegetables" },
    { id: 93, name: "Collard Greens", calories: 63, type: "vegetables" },
    { id: 94, name: "Swiss Chard", calories: 35, type: "vegetables" },
    { id: 95, name: "Arugula", calories: 5, type: "vegetables" },
    { id: 96, name: "Bok Choy", calories: 9, type: "vegetables" },
    { id: 97, name: "Napa Cabbage", calories: 13, type: "vegetables" },
    { id: 98, name: "Green Beans", calories: 31, type: "vegetables" },
    { id: 99, name: "Peas", calories: 62, type: "vegetables" },
    { id: 100, name: "Snow Peas", calories: 42, type: "vegetables" },
    { id: 101, name: "Snap Peas", calories: 26, type: "vegetables" },
    { id: 102, name: "Scallions", calories: 32, type: "vegetables" },
    { id: 103, name: "Shallot", calories: 72, type: "vegetables" },
    { id: 104, name: "Ginger", calories: 80, type: "vegetables" },
    { id: 105, name: "Horseradish", calories: 55, type: "vegetables" },
    { id: 106, name: "Daikon", calories: 18, type: "vegetables" },
    { id: 107, name: "Nori (Seaweed)", calories: 45, type: "vegetables" },
    { id: 108, name: "Fennel", calories: 27, type: "vegetables" },
    { id: 109, name: "Watercress", calories: 4, type: "vegetables" },
    { id: 110, name: "Endive", calories: 8, type: "vegetables" },
    { id: 111, name: "Chicory", calories: 23, type: "vegetables" },
    { id: 112, name: "Rutabaga", calories: 50, type: "vegetables" },
    { id: 113, name: "Yam", calories: 177, type: "vegetables" },
    { id: 114, name: "Taro", calories: 187, type: "vegetables" },
    { id: 115, name: "Bean Sprouts", calories: 31, type: "vegetables" },
    { id: 116, name: "Jalapeño", calories: 4, type: "vegetables" },
    { id: 117, name: "Serrano Pepper", calories: 6, type: "vegetables" },
    { id: 118, name: "Habanero", calories: 18, type: "vegetables" },
    { id: 119, name: "Olive", calories: 41, type: "vegetables" },
    { id: 120, name: "Kohlrabi", calories: 36, type: "vegetables" },

    { id: 121, name: "Rice", calories: 206, type: "grains" },
    { id: 122, name: "Brown Rice", calories: 216, type: "grains" },
    { id: 123, name: "Quinoa", calories: 222, type: "grains" },
    { id: 124, name: "Oats", calories: 150, type: "grains" },
    { id: 125, name: "Barley", calories: 193, type: "grains" },
    { id: 126, name: "Couscous", calories: 176, type: "grains" },
    { id: 127, name: "Millet", calories: 207, type: "grains" },
    { id: 128, name: "Wheat Bread", calories: 80, type: "grains" },
    { id: 129, name: "White Bread", calories: 79, type: "grains" },
    { id: 130, name: "Pasta", calories: 221, type: "grains" },
    { id: 131, name: "Bagel", calories: 245, type: "grains" },
    { id: 132, name: "Tortilla", calories: 150, type: "grains" },
    { id: 133, name: "Corn Tortilla", calories: 120, type: "grains" },
    { id: 134, name: "Crackers", calories: 70, type: "grains" },
    { id: 135, name: "Granola", calories: 200, type: "grains" },
    { id: 136, name: "Popcorn", calories: 55, type: "grains" },
    { id: 137, name: "Rye Bread", calories: 83, type: "grains" },
    { id: 138, name: "Cornbread", calories: 180, type: "grains" },
    { id: 139, name: "Buckwheat", calories: 155, type: "grains" },
    { id: 140, name: "Rice Noodles", calories: 192, type: "grains" },
    { id: 141, name: "Grits", calories: 182, type: "grains" },
    { id: 142, name: "Bulgur", calories: 151, type: "grains" },
    { id: 143, name: "Farro", calories: 200, type: "grains" },
    { id: 144, name: "Spelt", calories: 246, type: "grains" },
    { id: 145, name: "Sourdough Bread", calories: 120, type: "grains" },
    { id: 146, name: "Pita Bread", calories: 170, type: "grains" },
    { id: 147, name: "Naan", calories: 260, type: "grains" },
    { id: 148, name: "Udon Noodles", calories: 210, type: "grains" },
    { id: 149, name: "Soba Noodles", calories: 113, type: "grains" },
    { id: 150, name: "Vermicelli", calories: 220, type: "grains" },
    { id: 151, name: "Polenta", calories: 156, type: "grains" },
    { id: 152, name: "Breakfast Cereal", calories: 180, type: "grains" },
    { id: 153, name: "Muesli", calories: 150, type: "grains" },
    { id: 154, name: "Puffed Rice Cereal", calories: 130, type: "grains" },
    { id: 155, name: "Wheat Berries", calories: 160, type: "grains" },
    { id: 156, name: "Whole-Wheat Couscous", calories: 176, type: "grains" },
    { id: 157, name: "Brioche", calories: 150, type: "grains" },
    { id: 158, name: "Baguette", calories: 185, type: "grains" },
    { id: 159, name: "English Muffin", calories: 132, type: "grains" },
    { id: 160, name: "Pancake", calories: 90, type: "grains" },

    { id: 161, name: "Chicken Breast", calories: 165, type: "protein" },
    { id: 162, name: "Chicken Thigh", calories: 209, type: "protein" },
    { id: 163, name: "Beef Steak", calories: 271, type: "protein" },
    { id: 164, name: "Ground Beef", calories: 250, type: "protein" },
    { id: 165, name: "Pork Chop", calories: 242, type: "protein" },
    { id: 166, name: "Lamb", calories: 294, type: "protein" },
    { id: 167, name: "Turkey Breast", calories: 189, type: "protein" },
    { id: 168, name: "Salmon", calories: 206, type: "protein" },
    { id: 169, name: "Tuna", calories: 179, type: "protein" },
    { id: 170, name: "Shrimp", calories: 99, type: "protein" },
    { id: 171, name: "Egg", calories: 68, type: "protein" },
    { id: 172, name: "Tofu", calories: 144, type: "protein" },
    { id: 173, name: "Lentils", calories: 230, type: "protein" },
    { id: 174, name: "Chickpeas", calories: 269, type: "protein" },
    { id: 175, name: "Black Beans", calories: 227, type: "protein" },
    { id: 176, name: "Kidney Beans", calories: 215, type: "protein" },
    { id: 177, name: "Peanuts", calories: 161, type: "protein" },
    { id: 178, name: "Almonds", calories: 164, type: "protein" },
    { id: 179, name: "Cashews", calories: 155, type: "protein" },
    { id: 180, name: "Walnuts", calories: 185, type: "protein" },
    { id: 181, name: "Sunflower Seeds", calories: 165, type: "protein" },
    { id: 182, name: "Pumpkin Seeds", calories: 180, type: "protein" },
    { id: 183, name: "Tilapia", calories: 128, type: "protein" },
    { id: 184, name: "Crab", calories: 97, type: "protein" },
    { id: 185, name: "Clams", calories: 148, type: "protein" },
    { id: 186, name: "Mussels", calories: 172, type: "protein" },
    { id: 187, name: "Scallops", calories: 137, type: "protein" },
    { id: 188, name: "Duck", calories: 337, type: "protein" },
    { id: 189, name: "Goat Meat", calories: 143, type: "protein" },
    { id: 190, name: "Seitan", calories: 104, type: "protein" },
    { id: 191, name: "Tempeh", calories: 195, type: "protein" },
    { id: 192, name: "Edamame", calories: 122, type: "protein" },
    { id: 193, name: "Sardines", calories: 208, type: "protein" },
    { id: 194, name: "Mackerel", calories: 223, type: "protein" },
    { id: 195, name: "Herring", calories: 203, type: "protein" },
    { id: 196, name: "Anchovies", calories: 95, type: "protein" },
    { id: 197, name: "Trout", calories: 208, type: "protein" },
    { id: 198, name: "Cod", calories: 90, type: "protein" },
    { id: 199, name: "Haddock", calories: 112, type: "protein" },
    { id: 200, name: "Ham", calories: 139, type: "protein" },
    { id: 201, name: "Bacon", calories: 161, type: "protein" },
    { id: 202, name: "Turkey Sausage", calories: 196, type: "protein" },
    { id: 203, name: "Beef Jerky", calories: 116, type: "protein" },
    { id: 204, name: "Veal", calories: 238, type: "protein" },
    { id: 205, name: "Bison", calories: 124, type: "protein" },
    { id: 206, name: "Venison", calories: 159, type: "protein" },
    { id: 207, name: "Quail", calories: 234, type: "protein" },
    { id: 208, name: "Egg White", calories: 17, type: "protein" },
    { id: 209, name: "Peanut Butter", calories: 188, type: "protein" },
    { id: 210, name: "Almond Butter", calories: 190, type: "protein" },
    { id: 211, name: "Pistachios", calories: 159, type: "protein" },
    { id: 212, name: "Hazelnuts", calories: 178, type: "protein" },
    { id: 213, name: "Pecans", calories: 196, type: "protein" },
    { id: 214, name: "Macadamia Nuts", calories: 204, type: "protein" },
    { id: 215, name: "Brazil Nuts", calories: 187, type: "protein" },
    { id: 216, name: "Chia Seeds", calories: 137, type: "protein" },
    { id: 217, name: "Flax Seeds", calories: 150, type: "protein" },
    { id: 218, name: "Hemp Seeds", calories: 166, type: "protein" },
    { id: 219, name: "Sesame Seeds", calories: 168, type: "protein" },
    { id: 220, name: "Poppy Seeds", calories: 147, type: "protein" },
    { id: 221, name: "Navy Beans", calories: 255, type: "protein" },
    { id: 222, name: "Pinto Beans", calories: 245, type: "protein" },
    { id: 223, name: "Lima Beans", calories: 209, type: "protein" },
    { id: 224, name: "Split Peas", calories: 231, type: "protein" },
    { id: 225, name: "Black-Eyed Peas", calories: 200, type: "protein" },
    { id: 226, name: "Salami", calories: 119, type: "protein" },
    { id: 227, name: "Prosciutto", calories: 89, type: "protein" },
    { id: 228, name: "Pastrami", calories: 104, type: "protein" },
    { id: 229, name: "Bratwurst", calories: 283, type: "protein" },
    { id: 230, name: "Chorizo", calories: 273, type: "protein" },

    { id: 231, name: "Milk (Whole)", calories: 149, type: "dairy" },
    { id: 232, name: "Milk (Skim)", calories: 83, type: "dairy" },
    { id: 233, name: "Cheddar Cheese", calories: 113, type: "dairy" },
    { id: 234, name: "Mozzarella", calories: 85, type: "dairy" },
    { id: 235, name: "Yogurt", calories: 59, type: "dairy" },
    { id: 236, name: "Greek Yogurt", calories: 100, type: "dairy" },
    { id: 237, name: "Butter", calories: 102, type: "dairy" },
    { id: 238, name: "Cream Cheese", calories: 99, type: "dairy" },
    { id: 239, name: "Cottage Cheese", calories: 98, type: "dairy" },
    { id: 240, name: "Ice Cream", calories: 207, type: "dairy" },
    { id: 241, name: "Whipped Cream", calories: 52, type: "dairy" },
    { id: 242, name: "Parmesan", calories: 110, type: "dairy" },
    { id: 243, name: "Swiss Cheese", calories: 106, type: "dairy" },
    { id: 244, name: "Provolone", calories: 98, type: "dairy" },
    { id: 245, name: "Brie", calories: 95, type: "dairy" },
    { id: 246, name: "Ricotta", calories: 174, type: "dairy" },
    { id: 247, name: "Evaporated Milk", calories: 169, type: "dairy" },
    { id: 248, name: "Condensed Milk", calories: 321, type: "dairy" },
    { id: 249, name: "Kefir", calories: 104, type: "dairy" },
    { id: 250, name: "Buttermilk", calories: 98, type: "dairy" },
    { id: 251, name: "Ghee", calories: 112, type: "dairy" },
    { id: 252, name: "Sour Cream", calories: 60, type: "dairy" },
    { id: 253, name: "Half-and-Half", calories: 39, type: "dairy" },
    { id: 254, name: "Yogurt Drink", calories: 150, type: "dairy" },
    { id: 255, name: "Paneer", calories: 265, type: "dairy" },
    { id: 256, name: "Feta", calories: 75, type: "dairy" },
    { id: 257, name: "Goat Cheese", calories: 103, type: "dairy" },
    { id: 258, name: "Blue Cheese", calories: 100, type: "dairy" },
    { id: 259, name: "Mascarpone", calories: 120, type: "dairy" },
    { id: 260, name: "Queso Fresco", calories: 90, type: "dairy" },

    { id: 261, name: "Pizza", calories: 285, type: "junk food" },
    { id: 262, name: "Burger", calories: 354, type: "junk food" },
    { id: 263, name: "French Fries", calories: 365, type: "junk food" },
    { id: 264, name: "Hot Dog", calories: 151, type: "junk food" },
    { id: 265, name: "Fried Chicken", calories: 320, type: "junk food" },
    { id: 266, name: "Potato Chips", calories: 152, type: "junk food" },
    { id: 267, name: "Chocolate Bar", calories: 229, type: "junk food" },
    { id: 268, name: "Donut", calories: 195, type: "junk food" },
    { id: 269, name: "Candy", calories: 150, type: "junk food" },
    { id: 270, name: "Cake", calories: 250, type: "junk food" },
    { id: 271, name: "Ice Cream Sundae", calories: 300, type: "junk food" },
    { id: 272, name: "Nachos", calories: 346, type: "junk food" },
    { id: 273, name: "Brownie", calories: 243, type: "junk food" },
    { id: 274, name: "Cupcake", calories: 200, type: "junk food" },
    { id: 275, name: "Muffin", calories: 340, type: "junk food" },
    { id: 276, name: "Cinnamon Roll", calories: 313, type: "junk food" },
    { id: 277, name: "Pretzel (Soft)", calories: 389, type: "junk food" },
    { id: 278, name: "Corn Dog", calories: 225, type: "junk food" },
    { id: 279, name: "Funnel Cake", calories: 320, type: "junk food" },
    { id: 280, name: "Mozzarella Sticks", calories: 326, type: "junk food" },

    { id: 281, name: "Water", calories: 0, type: "drinks" },
    { id: 282, name: "Coffee", calories: 2, type: "drinks" },
    { id: 283, name: "Tea", calories: 2, type: "drinks" },
    { id: 284, name: "Orange Juice", calories: 112, type: "drinks" },
    { id: 285, name: "Apple Juice", calories: 114, type: "drinks" },
    { id: 286, name: "Soda", calories: 150, type: "drinks" },
    { id: 287, name: "Beer", calories: 153, type: "drinks" },
    { id: 288, name: "Wine", calories: 125, type: "drinks" },
    { id: 289, name: "Smoothie", calories: 200, type: "drinks" },
    { id: 290, name: "Milkshake", calories: 350, type: "drinks" },
    { id: 291, name: "Lemonade", calories: 120, type: "drinks" },
    { id: 292, name: "Iced Tea (Sweetened)", calories: 90, type: "drinks" },
    { id: 293, name: "Energy Drink", calories: 160, type: "drinks" },
    { id: 294, name: "Sports Drink", calories: 140, type: "drinks" },
    { id: 295, name: "Hot Chocolate", calories: 190, type: "drinks" },
    { id: 296, name: "Coconut Water", calories: 46, type: "drinks" },
    { id: 297, name: "Almond Milk", calories: 60, type: "drinks" },
    { id: 298, name: "Soy Milk", calories: 80, type: "drinks" },
    { id: 299, name: "Oat Milk", calories: 120, type: "drinks" },
    { id: 300, name: "Protein Shake", calories: 220, type: "drinks" },
  ];

  function handleClick(number: number) {
    const selectedFood = foodSelectorList[number];
    props.addFood(selectedFood);
  }
  return (
    <section className="w-1/2">
      <div className="flex justify-between">
        <ul className="flex">
          <li className="text-[#9A9A9A] font-bold">Fruits</li>
        </ul>
        <form action="">
          <input type="text" name="" id="" placeholder="Search..." />
        </form>
      </div>

      <ul className="h-50 overflow-y-scroll p-5 border">
        {foodSelectorList.map((food, index) => (
          <li>
            <button
              className="p-1 bg-white"
              onClick={() => handleClick(index)}
              key={index}
            >
              {food.name} +
            </button>
          </li>
        ))}
      </ul>
    </section>
  );
}
